### ISSUE TITLE
CI 적용

### ISSUE THREAD

**Issue by todoni** [42greenbox/front#1]
# TODO
## husky
- [x] pre-push(check lint)
- [x] pre-commit(auto formatting)
## prettier
- [x] .prettierrc.js 설정
## package.json
- [x] "format": "prettier --cache --write ."
