### ISSUE TITLE
legacy 버전에서 원래까지 되던 기능 까지는 되게 해놓기

### ISSUE THREAD

**Issue by todoni** [42greenbox/front#3]
# TODOS
## Scan
- [ ] 바코드 스캔기능
- [ ] 바코드 스캔 버튼을 누르면 scan 페이지로 이동하기
- [ ] 바코드 스캔이 끝나면 add 페이지로 돌아오기
## Add
- [ ] form 입력 받고 바코드 스캔 결과값 포함 하여 POST 요청 성공하기
- [ ] POST 요청 성공 후(시에만) 아이템 detail 페이지로 이동하기
## Takeout
- [ ] 아이템 detail 페이지에 takeout 버튼 추가
- [ ] 버튼 클릭시 현재 있는 페이지에 따라 (조건에 따라 ex. 내가 내껄 꺼내는지, 버리는지, etc. 페이지로도 구분가능) 해당하는 동작을 수행
- [ ] 완료(성공) 후 원래 있던 list(home or mylist)로 이동
## User
- [ ] Mypage 가면 user name과 point 보이게
