### ISSUE TITLE
ADVANCED FEATURES

### ISSUE THREAD

**Issue by todoni** [42greenbox/front#5]
## TODOS
- [ ] 바코드 인식 안될시 x버튼으로 닫고 직접 사진 찍거나 골라서 첨부할 수 있게
- [ ] 업로드한 사진 미리보기
- [ ] 각종 ui 예외처리 (빈 폼 제한 등)
- [ ] event confirm 되기 전 모달창으로 실행 여부 유저에게 한번 더 확인
